// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4RWt5_I82rngZWVwjlAwFBKSYvONj0BA',
    appId: '1:387397605372:web:c3aa887c5c419d01e80479',
    messagingSenderId: '387397605372',
    projectId: 'campusengine-d1168',
    authDomain: 'campusengine-d1168.firebaseapp.com',
    storageBucket: 'campusengine-d1168.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQvdzIYlhMf3-PO3kdt2vcoe1_kAMZ4KY',
    appId: '1:387397605372:android:3de9a5d82bdbda20e80479',
    messagingSenderId: '387397605372',
    projectId: 'campusengine-d1168',
    storageBucket: 'campusengine-d1168.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjea2p8MTQ-cBVkha9tFHhO5y7eRtLLnI',
    appId: '1:387397605372:ios:8e378e62f2001112e80479',
    messagingSenderId: '387397605372',
    projectId: 'campusengine-d1168',
    storageBucket: 'campusengine-d1168.firebasestorage.app',
    iosBundleId: 'com.sklproject.sklTeacher',
  );
}
